name: Checkout and List Files

on:
  push:

jobs:
  list_repo_files:
    runs-on: ubuntu-latest

    steps:
      # 1. Репозиторийді жүктеу
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Файлдардың тізімін шығару
      - name: Show repository files
  
